"""initial catalog schema

Revision ID: 0001
Revises:
Create Date: 2026-08-15 09:25:39.059661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_exported_curation_sequence', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('curation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('event_uuid', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('track_public_id', sa.String(), nullable=True),
    sa.Column('file_public_id', sa.String(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('curation_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_curation_events_event_uuid'), ['event_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_curation_events_file_public_id'), ['file_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_curation_events_sequence'), ['sequence'], unique=True)
        batch_op.create_index(batch_op.f('ix_curation_events_track_public_id'), ['track_public_id'], unique=False)

    op.create_table('files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('relative_path', sa.String(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('mtime_ns', sa.Integer(), nullable=False),
    sa.Column('extension', sa.String(), nullable=False),
    sa.Column('container_format', sa.String(), nullable=True),
    sa.Column('codec', sa.String(), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('title_raw', sa.String(), nullable=True),
    sa.Column('artist_raw', sa.String(), nullable=True),
    sa.Column('album_raw', sa.String(), nullable=True),
    sa.Column('album_artist_raw', sa.String(), nullable=True),
    sa.Column('genre_raw', sa.String(), nullable=True),
    sa.Column('bpm_raw', sa.String(), nullable=True),
    sa.Column('key_raw', sa.String(), nullable=True),
    sa.Column('comment_raw', sa.Text(), nullable=True),
    sa.Column('raw_metadata_json', sa.JSON(), nullable=True),
    sa.Column('resolved_artist', sa.String(), nullable=True),
    sa.Column('resolved_title', sa.String(), nullable=True),
    sa.Column('resolved_version', sa.String(), nullable=True),
    sa.Column('resolved_edition', sa.String(), nullable=True),
    sa.Column('artist_source', sa.String(), nullable=True),
    sa.Column('title_source', sa.String(), nullable=True),
    sa.Column('version_source', sa.String(), nullable=True),
    sa.Column('edition_source', sa.String(), nullable=True),
    sa.Column('binary_hash', sa.String(), nullable=True),
    sa.Column('binary_hash_status', sa.Enum('PENDING', 'CURRENT', 'STALE', 'ERROR', name='analysisstatus', native_enum=False), nullable=False),
    sa.Column('chromaprint', sa.Text(), nullable=True),
    sa.Column('chromaprint_duration_ms', sa.Integer(), nullable=True),
    sa.Column('chromaprint_status', sa.Enum('PENDING', 'CURRENT', 'STALE', 'ERROR', name='analysisstatus', native_enum=False), nullable=False),
    sa.Column('quality_status', sa.Enum('PENDING', 'CURRENT', 'STALE', 'ERROR', name='analysisstatus', native_enum=False), nullable=False),
    sa.Column('is_present', sa.Boolean(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('metadata_updated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_files_relative_path'), ['relative_path'], unique=True)

    op.create_table('scan_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'SUCCESS_WITH_ERRORS', 'FAILED', name='scanstatus', native_enum=False), nullable=False),
    sa.Column('files_seen', sa.Integer(), nullable=False),
    sa.Column('files_new', sa.Integer(), nullable=False),
    sa.Column('files_changed', sa.Integer(), nullable=False),
    sa.Column('files_unchanged', sa.Integer(), nullable=False),
    sa.Column('files_missing', sa.Integer(), nullable=False),
    sa.Column('files_failed', sa.Integer(), nullable=False),
    sa.Column('scanner_version', sa.String(), nullable=False),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scan_runs_public_id'), ['public_id'], unique=True)

    op.create_table('track_identity_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_uuid', sa.String(), nullable=False),
    sa.Column('event_type', sa.Enum('MERGE', 'SPLIT', 'UNMERGE', 'RESOLVE', name='identityeventtype', native_enum=False), nullable=False),
    sa.Column('source_track_public_id', sa.String(), nullable=False),
    sa.Column('target_track_public_id', sa.String(), nullable=True),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_identity_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_identity_events_event_uuid'), ['event_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_track_identity_events_source_track_public_id'), ['source_track_public_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_identity_events_target_track_public_id'), ['target_track_public_id'], unique=False)

    op.create_table('duplicate_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DETECTED', 'AUTO_CONFIRMED', 'REVIEW_REQUIRED', 'CONFIRMED', 'REJECTED', 'DEFERRED', name='duplicatestatus', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('proposed_preferred_file_id', sa.Integer(), nullable=True),
    sa.Column('matcher_version', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposed_preferred_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicate_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicate_groups_public_id'), ['public_id'], unique=True)

    op.create_table('file_featured_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('file_id', 'position')
    )
    with op.batch_alter_table('file_featured_artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_featured_artists_file_id'), ['file_id'], unique=False)

    op.create_table('file_quality_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('analyzer_version', sa.String(), nullable=False),
    sa.Column('integrity_status', sa.String(), nullable=False),
    sa.Column('lossless_status', sa.String(), nullable=False),
    sa.Column('transcode_suspicion', sa.Enum('NONE', 'LOW', 'MEDIUM', 'HIGH', name='transcodesuspicion', native_enum=False), nullable=False),
    sa.Column('clipping_status', sa.String(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('details_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('file_quality_analyses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_file_quality_analyses_file_id'), ['file_id'], unique=False)

    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PROVISIONAL', 'ACTIVE', 'MERGED', 'SUPERSEDED', name='trackstatus', native_enum=False), nullable=False),
    sa.Column('artist', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('edition', sa.String(), nullable=True),
    sa.Column('artist_normalized', sa.String(), nullable=True),
    sa.Column('title_normalized', sa.String(), nullable=True),
    sa.Column('version_normalized', sa.String(), nullable=True),
    sa.Column('edition_normalized', sa.String(), nullable=True),
    sa.Column('duration_reference_ms', sa.Integer(), nullable=True),
    sa.Column('preferred_file_id', sa.Integer(), nullable=True),
    sa.Column('identity_confidence', sa.Float(), nullable=True),
    sa.Column('merged_into_track_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['merged_into_track_id'], ['tracks.id'], ),
    sa.ForeignKeyConstraint(['preferred_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tracks_public_id'), ['public_id'], unique=True)

    op.create_table('duplicate_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.Enum('CONFIRM', 'CHANGE_PREFERRED', 'REJECT', 'DEFER', name='decisionaction', native_enum=False), nullable=False),
    sa.Column('preferred_file_id', sa.Integer(), nullable=True),
    sa.Column('report_id', sa.String(), nullable=False),
    sa.Column('catalog_revision', sa.String(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('payload_json', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['duplicate_groups.id'], ),
    sa.ForeignKeyConstraint(['preferred_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicate_decisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicate_decisions_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_decisions_public_id'), ['public_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_duplicate_decisions_report_id'), ['report_id'], unique=False)

    op.create_table('duplicate_group_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['duplicate_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'file_id')
    )
    with op.batch_alter_table('duplicate_group_members', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicate_group_members_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_group_members_group_id'), ['group_id'], unique=False)

    op.create_table('duplicate_pair_evidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('left_file_id', sa.Integer(), nullable=False),
    sa.Column('right_file_id', sa.Integer(), nullable=False),
    sa.Column('metadata_similarity', sa.Float(), nullable=True),
    sa.Column('artist_similarity', sa.Float(), nullable=True),
    sa.Column('title_similarity', sa.Float(), nullable=True),
    sa.Column('version_compatibility', sa.String(), nullable=True),
    sa.Column('edition_compatibility', sa.String(), nullable=True),
    sa.Column('featured_artist_similarity', sa.Float(), nullable=True),
    sa.Column('duration_delta_ms', sa.Integer(), nullable=True),
    sa.Column('binary_hash_equal', sa.Boolean(), nullable=True),
    sa.Column('chromaprint_similarity', sa.Float(), nullable=True),
    sa.Column('classification', sa.Enum('EXACT', 'AUDIO_EQUIVALENT', 'PROBABLE', 'DIFFERENT', 'CONFLICT', name='pairclassification', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('evidence_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['duplicate_groups.id'], ),
    sa.ForeignKeyConstraint(['left_file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['right_file_id'], ['files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('duplicate_pair_evidence', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_duplicate_pair_evidence_group_id'), ['group_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_pair_evidence_left_file_id'), ['left_file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_duplicate_pair_evidence_right_file_id'), ['right_file_id'], unique=False)

    op.create_table('track_featured_artists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('normalized_name', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'position')
    )
    with op.batch_alter_table('track_featured_artists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_featured_artists_track_id'), ['track_id'], unique=False)

    op.create_table('track_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.Column('relationship', sa.Enum('PRIMARY', 'EXACT_DUPLICATE', 'AUDIO_EQUIVALENT', 'PROBABLE', name='relationshiptype', native_enum=False), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('decision_source', sa.Enum('AUTOMATIC', 'HUMAN', name='decisionsource', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['files.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_files_file_id'), ['file_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_track_files_track_id'), ['track_id'], unique=False)
        batch_op.create_index('uq_track_files_one_active_per_file', ['file_id'], unique=True, sqlite_where=sa.text('is_active = 1'))

    op.create_table('track_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('field', sa.String(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('superseded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('track_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_track_overrides_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('track_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_overrides_track_id'))

    op.drop_table('track_overrides')
    with op.batch_alter_table('track_files', schema=None) as batch_op:
        batch_op.drop_index('uq_track_files_one_active_per_file', sqlite_where=sa.text('is_active = 1'))
        batch_op.drop_index(batch_op.f('ix_track_files_track_id'))
        batch_op.drop_index(batch_op.f('ix_track_files_file_id'))

    op.drop_table('track_files')
    with op.batch_alter_table('track_featured_artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_featured_artists_track_id'))

    op.drop_table('track_featured_artists')
    with op.batch_alter_table('duplicate_pair_evidence', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_pair_evidence_right_file_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_pair_evidence_left_file_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_pair_evidence_group_id'))

    op.drop_table('duplicate_pair_evidence')
    with op.batch_alter_table('duplicate_group_members', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_group_members_group_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_group_members_file_id'))

    op.drop_table('duplicate_group_members')
    with op.batch_alter_table('duplicate_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_decisions_report_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_decisions_public_id'))
        batch_op.drop_index(batch_op.f('ix_duplicate_decisions_group_id'))

    op.drop_table('duplicate_decisions')
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_public_id'))

    op.drop_table('tracks')
    with op.batch_alter_table('file_quality_analyses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_quality_analyses_file_id'))

    op.drop_table('file_quality_analyses')
    with op.batch_alter_table('file_featured_artists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_file_featured_artists_file_id'))

    op.drop_table('file_featured_artists')
    with op.batch_alter_table('duplicate_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_duplicate_groups_public_id'))

    op.drop_table('duplicate_groups')
    with op.batch_alter_table('track_identity_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_track_identity_events_target_track_public_id'))
        batch_op.drop_index(batch_op.f('ix_track_identity_events_source_track_public_id'))
        batch_op.drop_index(batch_op.f('ix_track_identity_events_event_uuid'))

    op.drop_table('track_identity_events')
    with op.batch_alter_table('scan_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scan_runs_public_id'))

    op.drop_table('scan_runs')
    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_relative_path'))
        batch_op.drop_index(batch_op.f('ix_files_public_id'))

    op.drop_table('files')
    with op.batch_alter_table('curation_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_curation_events_track_public_id'))
        batch_op.drop_index(batch_op.f('ix_curation_events_sequence'))
        batch_op.drop_index(batch_op.f('ix_curation_events_file_public_id'))
        batch_op.drop_index(batch_op.f('ix_curation_events_event_uuid'))

    op.drop_table('curation_events')
    op.drop_table('app_state')
    # ### end Alembic commands ###
